# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fdebdd3dc4ecefc501170b78c762051efa6e95eb889a235b095d71b8f3ee5bffa784cdb4ea09ed884526520092ad072350bd2952a48a7d395b62bc5e4167d1f

test:
  secret_key_base: 81b5c48f04bb8608e759a2bb6740beb88325dd0b5dc19f3fd850b1b44c8dab873e557372c44fd6fb690619f22ad2e71dc7bb510a91ded8e335bda78844f3f06b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
